PREFIX cac: <https://cacontology.projectvic.org#>

SELECT ?phase ?begin ?end
WHERE {
  ?inv a cac:CACInvestigation ;
       cac:hasPhase ?phase .
  ?phase cac:hasPhaseBeginPoint ?begin ;
         cac:hasPhaseEndPoint ?end .
}
ORDER BY ?begin
