"""Emit topology fluent helpers from Composition Profiles.

The C# / Java / Rust / Python helper surfaces are hand-maintained runtime
files in this repository. This module is the generator hook that:

* records the profile catalog used to emit them
* re-emits ``CompositionProfiles`` catalogs from ``topology/profiles/*.json``
  so profile IDs cannot drift
* is invoked on every ``generate`` (including IR cache hits) because the
  helpers do not depend on OWL parse.

Typed ontology classes remain generated by the language backends.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

PROFILE_IDS = (
    "MinimalForensics",
    "AirGappedFieldTriage",
    "HashIntelligence",
    "ToolMapping",
    "LegalProcess",
    "FullCACLifecycle",
    "CrossOntology",
)


def load_profile_catalog(repo_root: Path) -> list[dict[str, Any]]:
    profiles_dir = repo_root / "topology" / "profiles"
    catalog: list[dict[str, Any]] = []
    if not profiles_dir.is_dir():
        return [{"id": pid, "keywords": []} for pid in PROFILE_IDS]
    for pid in PROFILE_IDS:
        path = profiles_dir / f"{pid}.json"
        if not path.is_file():
            catalog.append({"id": pid, "keywords": []})
            continue
        raw = json.loads(path.read_text(encoding="utf-8"))
        catalog.append(
            {
                "id": raw["id"],
                "version": raw.get("version", "1.0.0"),
                "keywords": raw.get("keywords") or [],
                "air_gapped": raw.get("air_gapped", True),
            }
        )
    return catalog


def emit_topology_helpers(repo_root: Path) -> list[Path]:
    """Refresh generated profile catalogs. Runtime helper sources stay in-tree."""
    catalog = load_profile_catalog(repo_root)
    dest = repo_root / "generator" / "ir" / "profile-catalog.json"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps({"profiles": catalog}, indent=2) + "\n", encoding="utf-8")
    logger.info("Wrote topology profile catalog %s (%d profiles)", dest, len(catalog))
    return [dest]
